### ISSUE TITLE
Graphical bug in v1.2.2.0

### ISSUE THREAD

**Issue by Darthagnon** [vxiiduu/NotepadEx#3]
![npex64_BwmP9E7SfM](https://user-images.githubusercontent.com/20792748/187076062-e429c266-8c20-4541-88a9-fc88df5afe07.png)

Clicking on "File" will make the menu appear like this first; it fixes itself after hovering over the menu.

Win10 v1709, 100% scaling HiDPI with [DPI Fix](http://windows10-dpi-fix.xpexplorer.com/) and [Glass8.eu](https://web.archive.org/web/20220625201001/https://glass8.eu/), Nvidia 1060 MaxQ and Intel HD 630

**Comment by vxiiduu** [comment]
Unless you can reproduce this behavior on Windows 7, Vista, XP or 2000 it is not a bug.
I opened up a stock Windows 10 LTSC 2021 virtual machine and could not reproduce the problem either.

**Comment by win98se** [comment]
Could not reproduce the same behavior as well.
@Darthagnon Try opening a Windows Sandbox session (install it if you don't have it installed) and launch NotepadEx in it?
